#ifndef INDEX_HTML_H
#define INDEX_HTML_H

static const char INDEX_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>IC-JPEG - ESP32-CAM</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:'Segoe UI',system-ui,sans-serif;background:#1a1a2e;color:#eee;min-height:100vh}"
".header{background:#16213e;padding:16px 24px;border-bottom:2px solid #0f3460}"
".header h1{font-size:1.3em;color:#e94560}"
".header span{font-size:.85em;color:#888}"
".controls{background:#16213e;padding:12px 24px;display:flex;align-items:center;gap:16px;"
"border-bottom:1px solid #0f3460;flex-wrap:wrap}"
".controls label{font-size:.9em}"
".controls input[type=range]{width:200px}"
".q-val{font-weight:bold;color:#e94560;min-width:2.5em}"
".tabs{display:flex;background:#0f3460}"
".tab{flex:1;padding:12px;text-align:center;cursor:pointer;border:none;"
"background:transparent;color:#aaa;font-size:1em;transition:all .2s}"
".tab.active{background:#1a1a2e;color:#e94560;font-weight:bold;border-bottom:3px solid #e94560}"
".tab:hover{color:#fff}"
".content{display:flex;flex-wrap:wrap;justify-content:center;gap:24px;padding:24px}"
".img-container{border:2px solid #0f3460;border-radius:8px;overflow:hidden;background:#111}"
".img-container img{display:block;width:320px;height:240px;image-rendering:pixelated}"
".placeholder{width:320px;height:240px;display:flex;align-items:center;"
"justify-content:center;color:#555;font-style:italic}"
".metrics{background:#16213e;border-radius:8px;padding:20px;min-width:220px;"
"border:1px solid #0f3460}"
".metrics h3{margin-bottom:12px;color:#e94560;font-size:1em;"
"border-bottom:1px solid #0f3460;padding-bottom:8px}"
".metric-row{display:flex;justify-content:space-between;padding:6px 0;font-size:.9em}"
".metric-row .label{color:#aaa}"
".metric-row .value{font-weight:bold;color:#fff}"
".btn-capture{display:block;margin:0 auto;padding:12px 48px;background:#e94560;"
"color:#fff;border:none;border-radius:6px;font-size:1.1em;cursor:pointer;transition:background .2s}"
".btn-capture:hover{background:#c73652}"
".btn-capture:disabled{background:#555;cursor:wait}"
".status{text-align:center;padding:8px;font-size:.85em;color:#888}"
"</style>"
"</head>"
"<body>"
"<div class=\"header\">"
"<h1>IC-JPEG <span>v1.0.0 &mdash; ESP32-CAM DCT Comparison</span></h1>"
"</div>"
"<div class=\"controls\">"
"<label>Quality Factor:</label>"
"<input type=\"range\" id=\"quality\" min=\"1.0\" max=\"8.0\" step=\"0.5\" "
"value=\"2.0\" oninput=\"updateQuality(this.value)\">"
"<span class=\"q-val\" id=\"q-display\">2.0</span>"
"<span style=\"font-size:.8em;color:#666\">(1.0=high &hellip; 8.0=low)</span>"
"</div>"
"<div class=\"tabs\">"
"<button class=\"tab active\" onclick=\"selectTab('loeffler',this)\">Loeffler</button>"
"<button class=\"tab\" onclick=\"selectTab('matrix',this)\">Matrix</button>"
"<button class=\"tab\" onclick=\"selectTab('approx',this)\">Approx</button>"
"</div>"
"<div class=\"content\">"
"<div class=\"img-container\">"
"<div class=\"placeholder\" id=\"img-placeholder\">Press Capture</div>"
"<img id=\"preview\" style=\"display:none\" alt=\"Captured frame\">"
"</div>"
"<div class=\"metrics\">"
"<h3 id=\"metrics-title\">Metrics</h3>"
"<div class=\"metric-row\"><span class=\"label\">PSNR</span>"
"<span class=\"value\" id=\"m-psnr\">&mdash;</span></div>"
"<div class=\"metric-row\"><span class=\"label\">Bitrate</span>"
"<span class=\"value\" id=\"m-bitrate\">&mdash;</span></div>"
"<div class=\"metric-row\"><span class=\"label\">Compress</span>"
"<span class=\"value\" id=\"m-enc\">&mdash;</span></div>"
"<div class=\"metric-row\"><span class=\"label\">Decompress</span>"
"<span class=\"value\" id=\"m-dec\">&mdash;</span></div>"
"<div class=\"metric-row\"><span class=\"label\">Method</span>"
"<span class=\"value\" id=\"m-method\">&mdash;</span></div>"
"<div class=\"metric-row\"><span class=\"label\">Quality (k)</span>"
"<span class=\"value\" id=\"m-quality\">&mdash;</span></div>"
"</div>"
"</div>"
"<div style=\"padding:16px;text-align:center\">"
"<button class=\"btn-capture\" id=\"btn-capture\" onclick=\"doCapture()\">Capture</button>"
"</div>"
"<div class=\"status\" id=\"status\">Ready</div>"
"<script>"
"var currentMethod='loeffler';"
"function updateQuality(v){"
"document.getElementById('q-display').textContent=parseFloat(v).toFixed(1);}"
"function selectTab(method,el){"
"currentMethod=method;"
"document.querySelectorAll('.tab').forEach(function(t){t.classList.remove('active')});"
"el.classList.add('active');}"
"function doCapture(){"
"var btn=document.getElementById('btn-capture');"
"var status=document.getElementById('status');"
"btn.disabled=true;status.textContent='Capturing...';"
"var quality=document.getElementById('quality').value;"
"var url='/capture?method='+currentMethod+'&quality='+quality;"
"fetch(url).then(function(resp){"
"if(!resp.ok)throw new Error('HTTP '+resp.status);"
"var psnr=resp.headers.get('X-PSNR');"
"var bitrate=resp.headers.get('X-Bitrate');"
"var encTime=resp.headers.get('X-Compress-Time-Us');"
"var decTime=resp.headers.get('X-Decompress-Time-Us');"
"var method=resp.headers.get('X-Method');"
"var qf=resp.headers.get('X-Quality');"
"document.getElementById('m-psnr').textContent=psnr+' dB';"
"document.getElementById('m-bitrate').textContent=bitrate+' bpp';"
"document.getElementById('m-enc').textContent="
"(parseFloat(encTime)/1000).toFixed(1)+' ms';"
"document.getElementById('m-dec').textContent="
"(parseFloat(decTime)/1000).toFixed(1)+' ms';"
"document.getElementById('m-method').textContent=method;"
"document.getElementById('m-quality').textContent=qf;"
"return resp.blob();"
"}).then(function(blob){"
"var imgUrl=URL.createObjectURL(blob);"
"var img=document.getElementById('preview');"
"img.src=imgUrl;img.style.display='block';"
"document.getElementById('img-placeholder').style.display='none';"
"status.textContent='Capture complete';"
"}).catch(function(err){"
"status.textContent='Error: '+err.message;"
"}).finally(function(){btn.disabled=false;});}"
"</script>"
"</body>"
"</html>";

#endif /* INDEX_HTML_H */
